### ISSUE TITLE
bug with house unit o

### ISSUE THREAD

**Issue by sebastienvg** [petski/pimatic-mochad#7]
I wonder if that's only me but I noticed that 

 ansible-consul  master ✘ 17-11-27 19:54 echo "rf o1 on" | nc 192.168.79.140 1099
 ansible-consul  master ✘ 17-11-27 20:14 echo "rf o1 off" | nc 192.168.79.140 1099
11/28 01:14:20 Tx RF HouseUnit: O1 Func: Off
 ansible-consul  master ✘ 17-11-27 20:14 echo "rf o1 on" | nc 192.168.79.140 1099
 ansible-consul  master ✘ 17-11-27 20:14 echo "rf O1 on" | nc 192.168.79.140 1099
 ansible-consul  master ✘ 17-11-27 20:14 echo "rf o1 off" | nc 192.168.79.140 1099
11/28 01:14:52 Tx RF HouseUnit: O1 Func: Off

seems like unit O won't react to "1" only "0", works fine with every other house unit as far as I can tell.

**Comment by petski** [comment]
The service running on port 1099 is mochad, not pimatic-mochad. This issue seems to be related to mochad. I'd suggest you to report this bug at https://sourceforge.net/p/mochad/bugs/ (and send them the response of a "pl o1 on" command too).
